<?php

namespace AppBundle\Repository;

/**
 * BankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BankRepository extends \Doctrine\ORM\EntityRepository
{
    public function listPage($page, $pageLimit = 20, $condition)
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('a')
            ->from('AppBundle:Bank', 'a');
        $queryBuilder->andWhere('a.superior = :superior');
        $queryBuilder->setParameter('superior', $condition['superior']);
        if (!empty($condition['state'])) {
            $queryBuilder->andWhere('a.state = :state');
            $queryBuilder->setParameter('state', $condition['state']);
        }
        $query = $queryBuilder->orderBy('a.id', 'DESC')
            ->getQuery();
        $query->setFirstResult(($page - 1) * $pageLimit)
            ->setMaxResults($pageLimit);
        $paginator = new Paginator($query, $fetchJoinCollection = true);

        $result = [
            'count' => $paginator->count(),
            'pageCount' => ceil($paginator->count() / $pageLimit),
            'data' => $paginator->getIterator()
        ];
        return $result;

    }
}
