<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * BlacklistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlacklistRepository extends \Doctrine\ORM\EntityRepository
{
    public function listPage($page, $pageLimit = 20, $condition)
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('a')
            ->from('AppBundle:Blacklist', 'a');
        if (!empty($condition['name'])) {
            $queryBuilder->andWhere($queryBuilder->expr()->like('a.name', ':name'));
            $queryBuilder->setParameter('name', '%' . $condition['name'] . '%');
        }
        $query = $queryBuilder->orderBy('a.id', 'DESC')->getQuery();
        $query->setFirstResult(($page - 1) * $pageLimit)->setMaxResults($pageLimit);
        $paginator = new Paginator($query, $fetchJoinCollection = true);

        $result = [
            'count' => $paginator->count(),
            'pageCount' => ceil($paginator->count() / $pageLimit),
            'data' => $paginator->getIterator()
        ];
        return $result;

    }

    public function getAllAsArr()
    {
        $items = $this->_em->getRepository('AppBundle:Blacklist')->findAll();
        $names = [];
        foreach ($items as $item) {
            $names[] = $item->getName();
        }
        return $names;
    }
}
