<?php

namespace AppBundle\Repository;

/**
 * ClientConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientConfigRepository extends \Doctrine\ORM\EntityRepository
{
}
