<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CMTipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CMTipRepository extends \Doctrine\ORM\EntityRepository
{
    public function listPage($page, $pageLimit = 20, $condition)
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('c')
            ->from('AppBundle:CMTip', 'c');
        if (!empty($condition['keyword'])) {
            $queryBuilder->andWhere($queryBuilder->expr()->like('c.title', ':keyword'));
            $queryBuilder->setParameter('keyword', '%' . $condition['keyword'] . '%');
        }
        if (!empty($condition['state'])) {
            $queryBuilder->andWhere('c.state = :state');
            $queryBuilder->setParameter('state', $condition['state']);
        } else {
            $queryBuilder->andWhere('c.state = 1');
        }
        $query = $queryBuilder->orderBy('c.id', 'DESC')
            ->getQuery();
        $query->setFirstResult(($page - 1) * $pageLimit)
            ->setMaxResults($pageLimit);
        $paginator = new Paginator($query, $fetchJoinCollection = true);

        $result = [
            'count' => $paginator->count(),
            'pageCount' => ceil($paginator->count() / $pageLimit),
            'data' => $paginator->getIterator()
        ];
        return $result;
    }
}
