<?php

namespace AppBundle\Repository;

/**
 * FindingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FindingRepository extends \Doctrine\ORM\EntityRepository
{
}
