<?php

namespace AppBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function listPage($page, $pageLimit = 20, $condition)
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('m')
            ->from('AppBundle:Message', 'm');
        if (!empty($condition['to_user'])) {
            $queryBuilder->andWhere('m.toUser = :to_user');
            $queryBuilder->setParameter('to_user', $condition['to_user']);
        }
        $queryBuilder->andWhere('m.state != 2');
        $query = $queryBuilder->addOrderBy('m.state', 'ASC')->addOrderBy('m.id', 'DESC')
            ->getQuery();
        $query->setFirstResult(($page - 1) * $pageLimit)
            ->setMaxResults($pageLimit);
        $paginator = new Paginator($query, $fetchJoinCollection = true);

        $result = [
            'pageCount' => ceil($paginator->count() / $pageLimit),
            'data' => $paginator->getIterator()
        ];
        return $result;

    }
}
