<?php

namespace AppBundle\Repository;

/**
 * VCCompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VCCompanyRepository extends \Doctrine\ORM\EntityRepository
{
}
