nelmio_api_doc:
    name:                 'API documentation'
    exclude_sections:     []
    default_sections_opened:  true
    motd:
        template:             'NelmioApiDocBundle::Components/motd.html.twig'
    request_listener:
        enabled:              false
        parameter:            _doc
    sandbox:
        enabled:              true
        endpoint:             null
        accept_type:          null
        body_format:
            formats:

                # Defaults:
                - form
                - json
            default_format:       json # One of "form"; "json"
        request_format:
            formats:

                # Defaults:
                json:             application/json
            method:               accept_header # One of "format_param"; "accept_header"
            default_format:       json
        authentication:
            name:                 access_token
            delivery:             header

    cache:
        enabled:              false
        file:                 '%kernel.cache_dir%/api-doc.cache'