access:
    path:     /{catchall}
    defaults: { _controller: AppBundle:Default:index }
    requirements:
        catchall: .*
    methods:  [OPTIONS]

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
