# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 13
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        mysql_provider:
            entity:
                class: AppBundle:User
                property: token

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
        login:
            pattern: ^/((auth/)|(api_doc)|(cm_tip/search)|(client_config)|(resource/get)|(export/)|(_profiler))
            anonymous: ~
        main:
            guard:
                authenticators:
                    - app.token_authenticator
