# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.token_authenticator:
        class: AppBundle\Security\TokenAuthenticator
        arguments: ["@doctrine.orm.entity_manager"]
    app.user_voter:
        class: AppBundle\Voter\UserVoter
        tags:
            - { name: security.voter }
        # small performance boost
        public: false
    app.excel_io:
        class: AppBundle\Service\ExcelIOService
        arguments: ['@phpexcel']
    app.file_uploader:
        class: AppBundle\Service\FileUploader
        arguments: ['%uploaded_directory%']
    app.response_listener:
            class: AppBundle\Listener\ResponseListener
            tags:
                - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    app.qixin_api:
        class: AppBundle\Service\QiXinApi
        arguments: ["@guzzle.client.api_qixin007",'%qixin_appkey%']
    app.op_logger:
        class: AppBundle\Service\OperationLogger
        arguments: ["@security.token_storage",'@doctrine.orm.entity_manager']
#    app.push_service:
#        class: AppBundle\Service\PushService
    app.message_sender:
        class: AppBundle\Service\MessageSender
        arguments: ["@security.token_storage",'@doctrine.orm.entity_manager']
    app.loan_decision_helper:
        class: AppBundle\Service\LoanDecisionHelper
        arguments: ['@doctrine.orm.entity_manager',"@doctrine_mongodb"]

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
